Set Shell zsh
Output hwatch.gif
Require hwatch

Set FontSize 12
Set Width 900
Set Height 520
Set Padding 18
Set Framerate 30
Set TypingSpeed 90 ms
Set PlaybackSpeed 1.0
Set CursorBlink false
Set Theme "Catppuccin Frappe"
Set WindowBar Colorful

Type "hwatch --diff-plugin plugins/numeric-diff/target/release/libhwatch_plugin_numeric_diff.dylib -d numeric-diff sh ./img/demo-command.sh"
Enter
Sleep 15s
